//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDAEntities : DbContext
    {
        public QLDAEntities()
            : base("name=QLDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_banqlda> tbl_banqlda { get; set; }
        public virtual DbSet<tbl_banqlda_links> tbl_banqlda_links { get; set; }
        public virtual DbSet<tbl_chucvu> tbl_chucvu { get; set; }
        public virtual DbSet<tbl_chudautu> tbl_chudautu { get; set; }
        public virtual DbSet<tbl_cocauTMDT> tbl_cocauTMDT { get; set; }
        public virtual DbSet<tbl_cocautochucCDT> tbl_cocautochucCDT { get; set; }
        public virtual DbSet<tbl_congtrinh_hangmuc> tbl_congtrinh_hangmuc { get; set; }
        public virtual DbSet<tbl_duan> tbl_duan { get; set; }
        public virtual DbSet<tbl_giaingan_baocaoquy> tbl_giaingan_baocaoquy { get; set; }
        public virtual DbSet<tbl_giaingan_baocaoquy_files> tbl_giaingan_baocaoquy_files { get; set; }
        public virtual DbSet<tbl_giaingan_chitiet> tbl_giaingan_chitiet { get; set; }
        public virtual DbSet<tbl_giaingan_thuchien> tbl_giaingan_thuchien { get; set; }
        public virtual DbSet<tbl_goithau_coquanthanhtra> tbl_goithau_coquanthanhtra { get; set; }
        public virtual DbSet<tbl_goithau_dieuchinh> tbl_goithau_dieuchinh { get; set; }
        public virtual DbSet<tbl_goithau_kehoachlc> tbl_goithau_kehoachlc { get; set; }
        public virtual DbSet<tbl_goithau_loaihopdong> tbl_goithau_loaihopdong { get; set; }
        public virtual DbSet<tbl_goithau_thanhkiemtra> tbl_goithau_thanhkiemtra { get; set; }
        public virtual DbSet<tbl_goithau_thuchien> tbl_goithau_thuchien { get; set; }
        public virtual DbSet<tbl_goithau_trungthau> tbl_goithau_trungthau { get; set; }
        public virtual DbSet<tbl_goithau_trungthau_files> tbl_goithau_trungthau_files { get; set; }
        public virtual DbSet<tbl_goithau_trungthau_loaihopdong> tbl_goithau_trungthau_loaihopdong { get; set; }
        public virtual DbSet<tbl_hinhthuclc_nhathau> tbl_hinhthuclc_nhathau { get; set; }
        public virtual DbSet<tbl_hinhthucqlda> tbl_hinhthucqlda { get; set; }
        public virtual DbSet<tbl_linhvucdauthau> tbl_linhvucdauthau { get; set; }
        public virtual DbSet<tbl_loaiCDT> tbl_loaiCDT { get; set; }
        public virtual DbSet<tbl_loaihopdong> tbl_loaihopdong { get; set; }
        public virtual DbSet<tbl_loaitongmucdautu> tbl_loaitongmucdautu { get; set; }
        public virtual DbSet<tbl_mailconfigs> tbl_mailconfigs { get; set; }
        public virtual DbSet<tbl_nguonvon> tbl_nguonvon { get; set; }
        public virtual DbSet<tbl_phanbovon> tbl_phanbovon { get; set; }
        public virtual DbSet<tbl_phuongphapchonthau> tbl_phuongphapchonthau { get; set; }
        public virtual DbSet<tbl_phuongthucdauthau> tbl_phuongthucdauthau { get; set; }
        public virtual DbSet<tbl_thongbao> tbl_thongbao { get; set; }
        public virtual DbSet<tbl_thongbao_chitiet> tbl_thongbao_chitiet { get; set; }
        public virtual DbSet<tbl_tieuduan> tbl_tieuduan { get; set; }
        public virtual DbSet<tbl_tinh> tbl_tinh { get; set; }
        public virtual DbSet<tbl_tongmucdautu> tbl_tongmucdautu { get; set; }
        public virtual DbSet<tbl_vanban_cdt_coquanbh> tbl_vanban_cdt_coquanbh { get; set; }
        public virtual DbSet<tbl_vanban_coquanbanhanh> tbl_vanban_coquanbanhanh { get; set; }
        public virtual DbSet<tbl_vanban_files> tbl_vanban_files { get; set; }
        public virtual DbSet<tbl_vanban_loaivanban> tbl_vanban_loaivanban { get; set; }
        public virtual DbSet<tbl_vanban_quyetdinh> tbl_vanban_quyetdinh { get; set; }
        public virtual DbSet<tbl_von> tbl_von { get; set; }
        public virtual DbSet<tbl_von_dieuchinh> tbl_von_dieuchinh { get; set; }
        public virtual DbSet<tbl_von_giaidoan> tbl_von_giaidoan { get; set; }
        public virtual DbSet<tbl_z_file_images> tbl_z_file_images { get; set; }
        public virtual DbSet<tbl_z_folders> tbl_z_folders { get; set; }
        public virtual DbSet<tbl_z_logaccess> tbl_z_logaccess { get; set; }
        public virtual DbSet<tbl_z_permissions> tbl_z_permissions { get; set; }
        public virtual DbSet<tbl_z_roles> tbl_z_roles { get; set; }
        public virtual DbSet<tbl_z_users> tbl_z_users { get; set; }
        public virtual DbSet<tbl_z_maps> tbl_z_maps { get; set; }
    }
}
