//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goithau_thanhkiemtra
    {
        public int ID { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public Nullable<int> IdCoquanthanhtra { get; set; }
        public string Noidungthanhtra { get; set; }
        public Nullable<decimal> Thuhoi { get; set; }
        public Nullable<decimal> Thanhtoan { get; set; }
        public Nullable<decimal> Rasoatxuly { get; set; }
        public Nullable<int> Time_thuchien_from_month { get; set; }
        public Nullable<int> Time_thuchien_from_year { get; set; }
        public Nullable<int> Time_thuchien_to_month { get; set; }
        public Nullable<int> Time_thuchien_to_year { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_goithau_coquanthanhtra tbl_goithau_coquanthanhtra { get; set; }
        public virtual tbl_tieuduan tbl_tieuduan { get; set; }
    }
}
