//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goithau_trungthau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_goithau_trungthau()
        {
            this.tbl_goithau_kehoachlc = new HashSet<tbl_goithau_kehoachlc>();
        }
    
        public int ID { get; set; }
        public string Magoithau_trungthau { get; set; }
        public string Donvitrungthau { get; set; }
        public string Diachidonvitrungthau { get; set; }
        public Nullable<decimal> Dutoangoithau { get; set; }
        public Nullable<decimal> Giatrungthau { get; set; }
        public string QDchonthau_no { get; set; }
        public string QDchonthau_info { get; set; }
        public Nullable<System.DateTime> QDchonthau_time { get; set; }
        public string QDchonthau_files { get; set; }
        public Nullable<int> Time_thuchien_from_month { get; set; }
        public Nullable<int> Time_thuchien_from_year { get; set; }
        public Nullable<int> Time_thuchien_to_month { get; set; }
        public Nullable<int> Time_thuchien_to_year { get; set; }
        public Nullable<int> TimethuchienHDTT { get; set; }
        public Nullable<bool> Istypeday_timehd { get; set; }
        public Nullable<int> IdLoaihopdong { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_kehoachlc> tbl_goithau_kehoachlc { get; set; }
    }
}
