//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_giaingan_thuchien
    {
        public int ID { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public Nullable<int> Idgiaingan_chitiet { get; set; }
        public Nullable<int> ThangTHGN { get; set; }
        public Nullable<int> NamTHGN { get; set; }
        public string Noidungcongviec { get; set; }
        public string Khokhandenghi { get; set; }
        public string Filebaocaothang { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_giaingan_chitiet tbl_giaingan_chitiet { get; set; }
    }
}
