//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cocautochucCDT
    {
        public int ID { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public Nullable<int> IdBanqlda { get; set; }
        public Nullable<int> Chucvu { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PhoneCQ { get; set; }
        public string Fax { get; set; }
        public string Ghichu { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_banqlda tbl_banqlda { get; set; }
        public virtual tbl_chucvu tbl_chucvu { get; set; }
        public virtual tbl_chudautu tbl_chudautu { get; set; }
    }
}
