//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goithau_kehoachlc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_goithau_kehoachlc()
        {
            this.tbl_goithau_dieuchinh = new HashSet<tbl_goithau_dieuchinh>();
            this.tbl_goithau_thuchien = new HashSet<tbl_goithau_thuchien>();
        }
    
        public int ID { get; set; }
        public string Magoithau { get; set; }
        public string Tengoithau { get; set; }
        public Nullable<int> IdGoithau_trungthau { get; set; }
        public Nullable<int> IdGoithau_thuchien { get; set; }
        public Nullable<int> Idduan { get; set; }
        public Nullable<int> Idtieuduan { get; set; }
        public Nullable<int> IdNguonvon { get; set; }
        public Nullable<decimal> Giagoithau { get; set; }
        public Nullable<int> Time_thuchien_from_month { get; set; }
        public Nullable<int> Time_thuchien_from_year { get; set; }
        public Nullable<int> Time_thuchien_to_month { get; set; }
        public Nullable<int> Time_thuchien_to_year { get; set; }
        public Nullable<decimal> Time_HopDong { get; set; }
        public Nullable<bool> Istypeday_timehd { get; set; }
        public string QDkehoachthau_info { get; set; }
        public Nullable<System.DateTime> QDkehoachthau_time { get; set; }
        public string QDkehoachthau_no { get; set; }
        public string QDkehoachthau_files { get; set; }
        public Nullable<int> IdHinhthucluachonthau { get; set; }
        public Nullable<int> IdPhuongthucdauthau { get; set; }
        public Nullable<int> IdLinhvucdauthau { get; set; }
        public Nullable<int> IdLoaihopdong { get; set; }
        public Nullable<int> IdPhuongphapchonthau { get; set; }
        public Nullable<int> IdGoithau_thanhtra { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_duan tbl_duan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_dieuchinh> tbl_goithau_dieuchinh { get; set; }
        public virtual tbl_goithau_trungthau tbl_goithau_trungthau { get; set; }
        public virtual tbl_hinhthuclc_nhathau tbl_hinhthuclc_nhathau { get; set; }
        public virtual tbl_linhvucdauthau tbl_linhvucdauthau { get; set; }
        public virtual tbl_loaihopdong tbl_loaihopdong { get; set; }
        public virtual tbl_phuongphapchonthau tbl_phuongphapchonthau { get; set; }
        public virtual tbl_phuongthucdauthau tbl_phuongthucdauthau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_thuchien> tbl_goithau_thuchien { get; set; }
    }
}
