//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goithau_dieuchinh
    {
        public int ID { get; set; }
        public Nullable<int> Idgoithau_kehoachlc { get; set; }
        public string Sohopdong { get; set; }
        public Nullable<System.DateTime> Ngaykyhd { get; set; }
        public Nullable<decimal> Giahopdong { get; set; }
        public Nullable<int> Time_thuchien_from_month { get; set; }
        public Nullable<int> Time_thuchien_from_year { get; set; }
        public Nullable<int> Time_thuchien_to_month { get; set; }
        public Nullable<int> Time_thuchien_to_year { get; set; }
        public string Noidungdieuchinh { get; set; }
        public Nullable<decimal> Dieuchinhtanggiam { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_goithau_kehoachlc tbl_goithau_kehoachlc { get; set; }
    }
}
