//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_congtrinh_hangmuc
    {
        public int ID { get; set; }
        public Nullable<int> MaCongtrinh_hangmuc { get; set; }
        public string TenHienThi { get; set; }
        public Nullable<int> MaDuAn { get; set; }
        public Nullable<int> MaCDT { get; set; }
        public string Donvi { get; set; }
        public string Khoiluong { get; set; }
        public Nullable<int> IdGoithau { get; set; }
        public Nullable<int> Thutu { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_goithau_thuchien tbl_goithau_thuchien { get; set; }
    }
}
