//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chudautu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_chudautu()
        {
            this.tbl_banqlda = new HashSet<tbl_banqlda>();
            this.tbl_cocautochucCDT = new HashSet<tbl_cocautochucCDT>();
            this.tbl_giaingan_baocaoquy = new HashSet<tbl_giaingan_baocaoquy>();
            this.tbl_thongbao_chitiet = new HashSet<tbl_thongbao_chitiet>();
            this.tbl_tieuduan = new HashSet<tbl_tieuduan>();
            this.tbl_vanban_cdt_coquanbh = new HashSet<tbl_vanban_cdt_coquanbh>();
            this.tbl_vanban_quyetdinh = new HashSet<tbl_vanban_quyetdinh>();
            this.tbl_z_users = new HashSet<tbl_z_users>();
        }
    
        public int ID { get; set; }
        public string code { get; set; }
        public string MaCDT { get; set; }
        public string TenCDT { get; set; }
        public string TenCDTfull { get; set; }
        public string Diachi { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mota { get; set; }
        public Nullable<int> IdLoaiCDT { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_banqlda> tbl_banqlda { get; set; }
        public virtual tbl_loaiCDT tbl_loaiCDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cocautochucCDT> tbl_cocautochucCDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_baocaoquy> tbl_giaingan_baocaoquy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_thongbao_chitiet> tbl_thongbao_chitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tieuduan> tbl_tieuduan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vanban_cdt_coquanbh> tbl_vanban_cdt_coquanbh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vanban_quyetdinh> tbl_vanban_quyetdinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_z_users> tbl_z_users { get; set; }
    }
}
