//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_giaingan_chitiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_giaingan_chitiet()
        {
            this.tbl_giaingan_thuchien = new HashSet<tbl_giaingan_thuchien>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Ketquathuchien_xl { get; set; }
        public Nullable<decimal> Ketquathuchien_tv { get; set; }
        public Nullable<decimal> Ketquathuchien_gpmb { get; set; }
        public Nullable<decimal> Ketquagiaingan_xl { get; set; }
        public Nullable<decimal> Ketquagiaingan_tv { get; set; }
        public Nullable<decimal> Ketquagiaingan_gpmb { get; set; }
        public Nullable<decimal> Ketquahoanung_xl { get; set; }
        public Nullable<decimal> Ketquahoanung_tv { get; set; }
        public Nullable<decimal> Ketquahoanung_gpmb { get; set; }
        public Nullable<decimal> Kehoachthuchien_xl { get; set; }
        public Nullable<decimal> Kehoachthuchien_tv { get; set; }
        public Nullable<decimal> Kehoachthuchien_gpmb { get; set; }
        public Nullable<decimal> Kehoachgiaingan_xl { get; set; }
        public Nullable<decimal> Kehoachgiaingan_tv { get; set; }
        public Nullable<decimal> Kehoachgiaingan_gpmb { get; set; }
        public Nullable<decimal> Kehoachhoanung_xl { get; set; }
        public Nullable<decimal> Kehoachhoanung_tv { get; set; }
        public Nullable<decimal> Kehoachhoanung_gpmb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_thuchien> tbl_giaingan_thuchien { get; set; }
    }
}
