//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_giaingan_baocaoquy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_giaingan_baocaoquy()
        {
            this.tbl_giaingan_baocaoquy_files = new HashSet<tbl_giaingan_baocaoquy_files>();
            this.tbl_goithau_trungthau_files = new HashSet<tbl_goithau_trungthau_files>();
            this.tbl_z_file_images = new HashSet<tbl_z_file_images>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public Nullable<int> NamBC { get; set; }
        public string Kybaocao { get; set; }
        public string Urlfile { get; set; }
        public string Mota { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_duan tbl_duan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_baocaoquy_files> tbl_giaingan_baocaoquy_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_trungthau_files> tbl_goithau_trungthau_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_z_file_images> tbl_z_file_images { get; set; }
    }
}
