//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_z_folders
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string created_time { get; set; }
        public Nullable<int> Cate { get; set; }
    }
}
