//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_von
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_von()
        {
            this.tbl_von_dieuchinh = new HashSet<tbl_von_dieuchinh>();
        }
    
        public int ID { get; set; }
        public string Mavon { get; set; }
        public string Tenvon { get; set; }
        public Nullable<int> Maduan { get; set; }
        public Nullable<int> Matieuduan { get; set; }
        public Nullable<int> Magiaidoan { get; set; }
        public Nullable<decimal> Giatritien { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public Nullable<int> state { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_duan tbl_duan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_von_dieuchinh> tbl_von_dieuchinh { get; set; }
        public virtual tbl_von_giaidoan tbl_von_giaidoan { get; set; }
    }
}
