//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banqlda_links
    {
        public int ID { get; set; }
        public Nullable<int> IdBanqlda { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_banqlda tbl_banqlda { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_tieuduan tbl_tieuduan { get; set; }
    }
}
