//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_duan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_duan()
        {
            this.tbl_banqlda_links = new HashSet<tbl_banqlda_links>();
            this.tbl_giaingan_baocaoquy = new HashSet<tbl_giaingan_baocaoquy>();
            this.tbl_giaingan_baocaoquy1 = new HashSet<tbl_giaingan_baocaoquy>();
            this.tbl_giaingan_thuchien = new HashSet<tbl_giaingan_thuchien>();
            this.tbl_goithau_kehoachlc = new HashSet<tbl_goithau_kehoachlc>();
            this.tbl_goithau_thanhkiemtra = new HashSet<tbl_goithau_thanhkiemtra>();
            this.tbl_thongbao_chitiet = new HashSet<tbl_thongbao_chitiet>();
            this.tbl_tieuduan = new HashSet<tbl_tieuduan>();
            this.tbl_tongmucdautu = new HashSet<tbl_tongmucdautu>();
            this.tbl_vanban_quyetdinh = new HashSet<tbl_vanban_quyetdinh>();
            this.tbl_von = new HashSet<tbl_von>();
            this.tbl_tinh = new HashSet<tbl_tinh>();
        }
    
        public int Id { get; set; }
        public string code { get; set; }
        public string Maduan { get; set; }
        public string Diadiemkhobac { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public string Tenduan { get; set; }
        public int IdhinhthucQLDA { get; set; }
        public int Idloainguonvon { get; set; }
        public string Diadiemthuchien { get; set; }
        public string QDpheduyetDADT { get; set; }
        public string QDduyetCTDT { get; set; }
        public Nullable<System.DateTime> Ngaypheduyet { get; set; }
        public Nullable<System.DateTime> NgaypheduyetCTDT { get; set; }
        public decimal Tongmucdautu { get; set; }
        public string Urlfile { get; set; }
        public string Motaduan { get; set; }
        public Nullable<int> thang_khoicong { get; set; }
        public Nullable<int> nam_khoicong { get; set; }
        public Nullable<int> thang_hoanthanh { get; set; }
        public Nullable<int> nam_hoanthanh { get; set; }
        public Nullable<System.DateTime> Thoigiankhoicong { get; set; }
        public Nullable<System.DateTime> Thoigianhoanthanh { get; set; }
        public string UrlMaps { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> status { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_banqlda_links> tbl_banqlda_links { get; set; }
        public virtual tbl_hinhthucqlda tbl_hinhthucqlda { get; set; }
        public virtual tbl_nguonvon tbl_nguonvon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_baocaoquy> tbl_giaingan_baocaoquy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_baocaoquy> tbl_giaingan_baocaoquy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_giaingan_thuchien> tbl_giaingan_thuchien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_kehoachlc> tbl_goithau_kehoachlc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_thanhkiemtra> tbl_goithau_thanhkiemtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_thongbao_chitiet> tbl_thongbao_chitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tieuduan> tbl_tieuduan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tongmucdautu> tbl_tongmucdautu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vanban_quyetdinh> tbl_vanban_quyetdinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_von> tbl_von { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tinh> tbl_tinh { get; set; }
    }
}
