//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_von_dieuchinh
    {
        public int ID { get; set; }
        public Nullable<int> Mavon { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public Nullable<int> state { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public Nullable<decimal> Giatritien { get; set; }
    
        public virtual tbl_von tbl_von { get; set; }
    }
}
