//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vanban_quyetdinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vanban_quyetdinh()
        {
            this.tbl_vanban_files = new HashSet<tbl_vanban_files>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdCdt { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public Nullable<int> IdLoaivanban { get; set; }
        public Nullable<int> IdCoquanbh { get; set; }
        public Nullable<int> Idcdt_coquanbh { get; set; }
        public Nullable<int> VBQD_no_num { get; set; }
        public string VBQD_no_str { get; set; }
        public Nullable<System.DateTime> VBQD_time { get; set; }
        public string VBQD_info { get; set; }
        public string VBQD_files { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> type { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_tieuduan tbl_tieuduan { get; set; }
        public virtual tbl_vanban_cdt_coquanbh tbl_vanban_cdt_coquanbh { get; set; }
        public virtual tbl_vanban_coquanbanhanh tbl_vanban_coquanbanhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vanban_files> tbl_vanban_files { get; set; }
        public virtual tbl_vanban_loaivanban tbl_vanban_loaivanban { get; set; }
    }
}
