//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tieuduan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tieuduan()
        {
            this.tbl_banqlda_links = new HashSet<tbl_banqlda_links>();
            this.tbl_goithau_thanhkiemtra = new HashSet<tbl_goithau_thanhkiemtra>();
            this.tbl_tongmucdautu = new HashSet<tbl_tongmucdautu>();
            this.tbl_vanban_quyetdinh = new HashSet<tbl_vanban_quyetdinh>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Maduan { get; set; }
        public Nullable<int> MaCDT { get; set; }
        public string Matieuduan { get; set; }
        public string Tentieuduan { get; set; }
        public string Diadiemkhobac { get; set; }
        public string Mota { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_banqlda_links> tbl_banqlda_links { get; set; }
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_thanhkiemtra> tbl_goithau_thanhkiemtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tongmucdautu> tbl_tongmucdautu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vanban_quyetdinh> tbl_vanban_quyetdinh { get; set; }
    }
}
