//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banqlda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_banqlda()
        {
            this.tbl_banqlda_links = new HashSet<tbl_banqlda_links>();
            this.tbl_cocautochucCDT = new HashSet<tbl_cocautochucCDT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public string Mabanqlda { get; set; }
        public string Tenbanqlda { get; set; }
        public string Diachi { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mota { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_banqlda_links> tbl_banqlda_links { get; set; }
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cocautochucCDT> tbl_cocautochucCDT { get; set; }
    }
}
