//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tongmucdautu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_tongmucdautu()
        {
            this.tbl_cocauTMDT = new HashSet<tbl_cocauTMDT>();
        }
    
        public int ID { get; set; }
        public string MaTMDT { get; set; }
        public Nullable<decimal> GiatridutoanTMDT { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdTieuduan { get; set; }
        public Nullable<int> Landieuchinh { get; set; }
        public Nullable<int> state { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
        public string QDDuyetDC { get; set; }
        public Nullable<System.DateTime> ThoigianQDPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cocauTMDT> tbl_cocauTMDT { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_tieuduan tbl_tieuduan { get; set; }
    }
}
