//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_z_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_z_users()
        {
            this.tbl_z_logaccess = new HashSet<tbl_z_logaccess>();
            this.tbl_z_roles1 = new HashSet<tbl_z_roles>();
        }
    
        public int User_Id { get; set; }
        public Nullable<int> IdRole { get; set; }
        public Nullable<int> IdChudautu { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        public string Mail { get; set; }
        public string token { get; set; }
    
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_z_logaccess> tbl_z_logaccess { get; set; }
        public virtual tbl_z_roles tbl_z_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_z_roles> tbl_z_roles1 { get; set; }
    }
}
