//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_goithau_coquanthanhtra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_goithau_coquanthanhtra()
        {
            this.tbl_goithau_thanhkiemtra = new HashSet<tbl_goithau_thanhkiemtra>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MaCoquanthanhtra { get; set; }
        public string TenCoquanthanhtra { get; set; }
        public string Mota { get; set; }
        public Nullable<int> Order_key { get; set; }
        public string Nguoitao { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public string Nguoisua { get; set; }
        public Nullable<System.DateTime> Ngaysua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_goithau_thanhkiemtra> tbl_goithau_thanhkiemtra { get; set; }
    }
}
