//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_thongbao_chitiet
    {
        public int ID { get; set; }
        public Nullable<int> IdNotification { get; set; }
        public Nullable<int> IdDuan { get; set; }
        public Nullable<int> IdCDT { get; set; }
    
        public virtual tbl_chudautu tbl_chudautu { get; set; }
        public virtual tbl_duan tbl_duan { get; set; }
        public virtual tbl_thongbao tbl_thongbao { get; set; }
    }
}
